"""add hardware_id to device

Revision ID: 46ad5259340d
Revises: bb66b9b3f9d5
Create Date: 2026-03-03 11:45:25.031406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46ad5259340d'
down_revision = 'bb66b9b3f9d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hardware_id', sa.String(length=128), nullable=True))
        batch_op.create_index(batch_op.f('ix_device_hardware_id'), ['hardware_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_hardware_id'))
        batch_op.drop_column('hardware_id')

    # ### end Alembic commands ###
