"""add api_key to device

Revision ID: bb66b9b3f9d5
Revises: 
Create Date: 2026-03-03 11:30:11.260186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb66b9b3f9d5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_key', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_device_api_key'), ['api_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_device_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_device_name'), ['device_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_last_online'), ['last_online'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_status'), ['status'], unique=False)
        batch_op.create_index('ix_device_status_online', ['status', 'last_online'], unique=False)

    with op.batch_alter_table('device_playlist', schema=None) as batch_op:
        batch_op.create_index('ix_device_playlist_active', ['device_id', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_playlist_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_playlist_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_playlist_playlist_id'), ['playlist_id'], unique=False)

    with op.batch_alter_table('device_schedule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_schedule_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_schedule_is_enabled'), ['is_enabled'], unique=False)

    with op.batch_alter_table('media_file', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_media_file_file_name'), ['file_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_file_file_type'), ['file_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_file_folder_id'), ['folder_id'], unique=False)
        batch_op.create_index('ix_media_file_folder_type', ['folder_id', 'file_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_file_md5_hash'), ['md5_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_file_status'), ['status'], unique=False)
        batch_op.create_index('ix_media_file_status_upload', ['status', 'upload_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_file_upload_time'), ['upload_time'], unique=False)

    with op.batch_alter_table('media_folder', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_media_folder_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_folder_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index('ix_media_folder_parent_name', ['parent_id', 'name'], unique=False)

    with op.batch_alter_table('playlist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_playlist_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_playlist_name'), ['name'], unique=False)

    with op.batch_alter_table('playlist_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_playlist_item_media_id'), ['media_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_playlist_item_playlist_id'), ['playlist_id'], unique=False)
        batch_op.create_index('ix_playlist_item_playlist_order', ['playlist_id', 'display_order'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlist_item', schema=None) as batch_op:
        batch_op.drop_index('ix_playlist_item_playlist_order')
        batch_op.drop_index(batch_op.f('ix_playlist_item_playlist_id'))
        batch_op.drop_index(batch_op.f('ix_playlist_item_media_id'))

    with op.batch_alter_table('playlist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_playlist_name'))
        batch_op.drop_index(batch_op.f('ix_playlist_created_at'))

    with op.batch_alter_table('media_folder', schema=None) as batch_op:
        batch_op.drop_index('ix_media_folder_parent_name')
        batch_op.drop_index(batch_op.f('ix_media_folder_parent_id'))
        batch_op.drop_index(batch_op.f('ix_media_folder_name'))

    with op.batch_alter_table('media_file', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_media_file_upload_time'))
        batch_op.drop_index('ix_media_file_status_upload')
        batch_op.drop_index(batch_op.f('ix_media_file_status'))
        batch_op.drop_index(batch_op.f('ix_media_file_md5_hash'))
        batch_op.drop_index('ix_media_file_folder_type')
        batch_op.drop_index(batch_op.f('ix_media_file_folder_id'))
        batch_op.drop_index(batch_op.f('ix_media_file_file_type'))
        batch_op.drop_index(batch_op.f('ix_media_file_file_name'))

    with op.batch_alter_table('device_schedule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_schedule_is_enabled'))
        batch_op.drop_index(batch_op.f('ix_device_schedule_device_id'))

    with op.batch_alter_table('device_playlist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_playlist_playlist_id'))
        batch_op.drop_index(batch_op.f('ix_device_playlist_is_active'))
        batch_op.drop_index(batch_op.f('ix_device_playlist_device_id'))
        batch_op.drop_index('ix_device_playlist_active')

    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.drop_index('ix_device_status_online')
        batch_op.drop_index(batch_op.f('ix_device_status'))
        batch_op.drop_index(batch_op.f('ix_device_last_online'))
        batch_op.drop_index(batch_op.f('ix_device_device_name'))
        batch_op.drop_index(batch_op.f('ix_device_created_at'))
        batch_op.drop_index(batch_op.f('ix_device_api_key'))
        batch_op.drop_column('api_key')

    # ### end Alembic commands ###
